software/mk/Makefile.builddefs, software/mk/Makefile.tail_rules, software/spmd/Makefile, software/spmd/Makefile.include, software/spmd/bsg_remote_congestion/Makefile, software/spmd/hello/Makefile
Makefile rule to archive bsg_manycore_lib for static linking.
One complication: the `.a` target added in `Makefile.buidldefs` was begin considered as the default target, instead of `all` in the Makefile including it. Hence, I figured it's a good practice to add `.DEFAULT_GOAL = <default target>` as the first line of any Makefile including other Makefiles. But since existing Makefiles didn't do that, I added `.DEFAULT_GOAL = all` in `Makefile.include`. And, regression passed without any issues.
=> Lib archive

software/spmd/.gitignore, software/spmd/Makefile.regress.list, software/spmd/coremark/Makefile, software/spmd/fib/Makefile, software/spmd/fib/main.c, software/spmd/regfile_x0_test/Makefile, software/spmd/regfile_x0_test/main.S, v/vanilla_bean/definitions.vh, v/vanilla_bean/hobbit.v, v/vanilla_bean/rf_2r1w_sync_wrapper.v
- including x0 logic in regfile module
- test to verify x0 operation
compare with https://github.com/bespoke-silicon-group/bsg_manycore/pull/9
```
coremark score = unchanged
area: 
Combinational area:              17496.410647
Buf/Inv area:                     4098.477703
Noncombinational area:           14031.032654
Macro/Black Box area:            78908.887695
Total cell area:                110436.330996
power:
Internal         Switching           Leakage            Total
Power Group      Power            Power               Power              Power   (   %    )  Attrs
--------------------------------------------------------------------------------------------------
io_pad             0.0000            0.0000            0.0000            0.0000  (   0.00%)
memory             4.0053 …
```
=> Regfile x0

software/bsg_manycore_lib/bsg_set_tile_x_y.c
__bsg_id is being calculated incorrectly. This was based on the assumption that X/Y dimensions of the manycore are always the same, which is no longer true. 
Regression tests passed. Ready to merge.
=> Bug fix bsg_id calculation from __bsg_x/y

software/mk/Makefile.verilog
including bsg_cadenv is unnecessary for F1 Cosimulation. Cloning it isn't currently isn't part of the Bladerunner flow.
So, I've added a variable that allows VCS/DVE/Cadenv to be ignored.
=> Added a Variable that allows cadenv to be ignored in Makefile.verilog

software/bsg_manycore_lib/bsg_cuda_lite_runtime.h, software/spmd/bsg_cuda_lite_runtime/matrix_mul/kernel_matrix_mul.c
This PR addresses issue #175 on bsg_f1.
Introduced 6 new symbols in the bsg_cuda_lite_runtime.h header file, cuda_kernel_ptr, cuda_argc, cuda_argv_ptr, cuda_finish_signal_addrl, cuda_finish_signal_val and cuda_kernel_not_loaded_val. The symbols are set by the CUDA API after binary is loaded onto tiles. 
**Should only be merged in together with PR #298 on bsg_f1**
=> Added CUDA runtime symbols that are set by host's CUDA API

machines/1x1/Makefile.machine.include, machines/2x2/Makefile.machine.include, machines/4x4/Makefile.machine.include, machines/Makefile, software/mk/Makefile.builddefs, software/spmd/beebs/Makefile, software/spmd/common/link_dmem.ld, software/spmd/common/link_dmem2.ld, software/spmd/common/link_dram.ld, software/spmd/common/link_dram2.ld, software/spmd/fhello/Makefile
- `BSG_ELF_OFF_CHIP_MEM = {0|1}`:  0 => Only use vcache EVA range, 1 => use DRAM EVA range
- `BSG_ELF_DEFAULT_DATA_LOC = {LOCAL|SHARED}`:  Default location of data section; `LOCAL`=>DMEM, `SHARED`=DRAM/VCACHE.
- `BSG_ELF_DRAM_SIZE`: Total DRAM size
- `BSG_ELF_VCACHE_SIZE`: Total VCACHE size
- `BSG_ELF_STACK_PTR`:  If data section is in dmem, `= 0x1ffc`, else if dram exists `=BSG_DRAM_SIZE-4`, else `=BSG_VCACHE_SIZE-4`
=> Manycore ELF configuration options

testbenches/common/v/bsg_nonsynth_manycore_io_complex.v, testbenches/common/v/bsg_nonsynth_manycore_spmd_loader.v
Expose loader_done signal to testbench, so that we can reduce manycore clock frequency when loading program to speed up simulation
=> Expose spmd_loader_done signal to outside world

software/bsg_manycore_lib/bsg_manycore.h, software/bsg_manycore_lib/bsg_manycore_arch.h, software/spmd/bsg_cuda_lite_runtime/float_vec_add_shared_mem/Makefile, software/spmd/bsg_cuda_lite_runtime/float_vec_add_shared_mem/kernel_float_vec_add_shared_mem.c, software/spmd/bsg_cuda_lite_runtime/float_vec_add_shared_mem/main.c, software/spmd/bsg_cuda_lite_runtime/matrix_mul_shared_mem/kernel_matrix_mul_shared_mem.c, software/spmd/bsg_cuda_lite_runtime/shared_mem/kernel_shared_mem.c, software/spmd/bsg_cuda_lite_runtime/shared_mem_load_store/kernel_shared_mem_load_store.c, software/spmd/bsg_cuda_lite_runtime/vec_add_shared_mem/kernel_vec_add_shared_mem.c, software/spmd/bsg_tile_group_mem/main.c
1. Modified bsg_tile_group_shared_load/store macros to also take in the type (int or float) as input argument. 
2. Added a bsg_tile_group_remote_ptr macro that translates to a bsg_remote_int/float_ptr based on the given argument. 
3. Added a floating point vector addition with tile group shared memory cuda lite runtime regression test.
=> Refactor tile group shared memory to support floating point

machines/Makefile, software/riscv-tools/Makefile, software/riscv-tools/README.md
- Added `f` extension to target ISA for riscv-gnu-toolchain installation.
- Added `install-clean` and `install-with-builds` to install tools without and with builds preserved respectively.
- Updated readme.
=> Toolchain updates

software/bsg_manycore_lib/bsg_cuda_lite_runtime.h
Fixed the race bug related to bsg_set_tile_x_y() that was being called at the beginning of cuda lite runtime binary loaded into tiles, the function initializes bsg_x/y/id/tile_group_id symbols, but is too slow in cosim, and is not done when the host starts sending the correct values for symbols, causing the symbols to take the wrong values. 
There is no longer a need to call bsg_set_tile_x_y() in cuda_lite kernels, therefore it is removed.
Credit and huge thanks to @drichmond for his help!
=> Fixed bug in bsg_cuda_lite_runtime.h

software/bsg_manycore_lib/bsg_tilegroup.h, software/manycore-llvm-pass/manycore/Manycore.cpp, software/spmd/striped_hello/main.c
This fixes the issue with the `striped_hello` spmd test timing out (#114) by making the LLVM pass respect the programmer's use of `volatile`, as well as fixing an issue where the test wasn't agnostic to manycore size.
=> Volatile load bugfix

machines/4x4/Makefile.machine.include, machines/9x15/Makefile.machine.include, machines/Makefile, machines/arch_filelist.mk, software/bsg_manycore_lib/bsg_manycore.h, software/spmd/hello/main.c, testbenches/common/v/bsg_nonsynth_manycore_monitor.v, testbenches/common/v/spmd_testbench.v, v/bsg_manycore.v, v/bsg_manycore_addr_pkg.v, v/bsg_manycore_hetero_socket.v, v/bsg_manycore_tile.v, v/vanilla_bean/bsg_manycore_proc_vanilla.v, v/vanilla_bean/lsu.v, v/vanilla_bean/vanilla_core.v
- Mapped EPA=0xEEE0 to stderr to have separate streams for program output and trace. Also, Newlib std streams could be separated.
- New bsg_manycore_lib macro bsg_putchar_err to write char to stderr stream.
=> Parameterized HW tracing of Branch & JALR target-PCs

software/spmd/putchar_stream/Makefile, software/spmd/putchar_stream/main.c
A simple program to push the IO interface to limits -- fills up fifos in IO interface and network routers and cause a stall in the core. This uncovered a minor issue in bsg_f1's fifo interface where credits are being returned even when the fifo is full.
=> Simple program to test fast heavy printing

software/spmd/specint2000/Makefile, software/spmd/specint2000/Makefile.000.plain, software/spmd/specint2000/Makefile.000.test, software/spmd/specint2000/Makefile.175.vpr, software/spmd/specint2000/Makefile.300.twolf, software/spmd/specint2000/Makefile.common, software/spmd/specint2000/README.md
Removed greenlight submodule as it is not open sourced. And added a rule in specint Makefile to clone it when necessary.
=> Removed greenlight submodule

Makefile, software/riscv-tools/Makefile
- Fix building toolchain scripts. The correct toolchain path is
'software/riscv-tools' instead of 'software/spmd/riscv-tools'.
- Remove '--remote' from git submodule command in
'software/riscv-tools/Makefile' for compatability with Centos 6.
'--remote' only works with git version 2.x.
Git version 1.7x such as the one on Centos 6 does not have this options.
=> Fix toolchain-building script

software/riscv-tools/Makefile, software/riscv-tools/newlib.patch
- Patch riscv-gnu-toolchain to fix a installation issue.
- Added target cflags -- this fixes expf issue!!
https://github.com/bespoke-silicon-group/bsg_manycore/blob/8e93b73a7a87ab11f348b3ec629dd79df9288d6b/software/riscv-tools/Makefile#L32
BSG Manycore's FPU needs a set of gcc flags, because it don't implement fused mul-add, fexp etc. We have those options in our C compilation flow. The issue was, they were not added to the library compilation flow, which caused the math library to be compiled assuming fma (fused mul-add) instructions are legal. Since we don't support fma instructions, expf which had fma instructions in it's compiled binary produces wrong results on our hardware. This addition tells the toolchain build flow to compile library code with provided cflags.
- Added back …
=> Toolchain newlib patch

software/spmd/bsg_cuda_lite_runtime/binary_load_buffer/Makefile, software/spmd/bsg_cuda_lite_runtime/binary_load_buffer/kernel_binary_load_buffer.c, software/spmd/bsg_cuda_lite_runtime/binary_load_buffer/main.c
instead of loading binary from a file in a given path. 
Related to PR # 419 in bsg_f1.
=> Added cuda lite runtime regression test to load binary from pre-loaded buffer

software/mk/.gitignore, software/mk/Makefile.builddefs, software/mk/Makefile.llvminstall, software/riscv-tools/.gitignore, software/riscv-tools/Makefile
I've removed the dependence that LLVM_DIR be a globally accessible directory. Now, it is built with the RISC-V tools on a clean installation. 
This makes bsg_manycore immediately portable to kk9, and simplifies the aws build process (a bit)
This also updates to cmake3 (instead of cmake) which means we no longer need to download and build cmake.
=> Fix LLVM installation

software/spmd/bsg_cuda_lite_runtime/softmax/kernel_softmax.c
This was a leftover from debugging. Not super sure how it passed with this line, but it still passes when I remove it. 
Maybe we need to somehow have a smarter way of testing kernels?
=> Stop kernel_softmax from returning early.

software/bsg_manycore_lib/bsg_manycore.h
Currently we can't call bsg_printf from c++ code. Adding this declaration solves the problem, BUT I'm not sure if it's too heavy handed. I included the whole file which is probably unnecessary.
=> Added extern c to bsg_manycore.h

software/py/blood_graph.py
Modified blood graph to automatically parse the vanilla_stats.csv file to get the start and end cycles, instead of having to pass it in by hand with the --cycle start_time@end_time argument.
New way of calling bloodgraph:
python3 blood_graph.py --input vanilla_operation_trace.csv --timing-stats vanilla_stats.csv
=> Automatic Timing parser for blood graph

software/py/vanilla_stats_parser.py
Just converts some things into float64 to make division by 0 not throw exception.
=> Fix stats parser when dealing with no stalls

software/spmd/common/link_dmem.ld
One of my kernels had a `.data.dram` section size of 97 bytes, which caused it to fail to load program onto manycore.
=> Fix linker script to force sections to be word-aligned

software/py/blood_graph.py, software/py/vanilla_stats_parser.py
Adds a new field to the vanilla stats parser reports, that count the absolute parallel cycle count as opposed to the existing aggregate cycle count.
In other words, when multiple tiles participate in a tag / kernel in parallel, it counts the longest parallel interval, from when the earliest tile starts running until when the latest tile stop running in that region.
Adds absolute cycle count for both manycore stats and tile group stats. Naturally, for tile stats, the absolute cycle count is equal to the aggregate cycle count.
=> Adds absolute parallel cycle count to vanilla stats parser

v/vanilla_bean/vanilla_core.v
These print statements are constant in CUDA programs. They're annoying to work with because they can interfere with debug messages from the manycore and they're no longer useful (at least, until we need to debug kernel launching again)
=> Removed [INFO][VCORE] print statements

testbenches/common/v/vcache_non_blocking_profiler.v, testbenches/common/v/vcache_profiler.v
Changed the output of both vcache_profiler.v and vcache_non_blocking_profiler.v to the same file, "vcache_stats.csv", for simplicity of parsing in the bladerunner and bsg_replicant, since only one gets generated for every simulation based on the vcache that is used.
=> Changed the output of both blocking and non-blocking vcache profiler's

software/py/blood_graph.py, software/py/vanilla_stats_parser.py
Asserts to make sure there are traces in the vanilla_stats_parser, prints out error if it is empty.
Minor color updates for bloodgraph.
=> Added safeguard for vanilla stats parser against empty stats

software/py/vanilla_pc_histogram.py, software/py/vanilla_stats_parser.py, testbenches/common/v/spmd_testbench.v, testbenches/common/v/vanilla_core_profiler.v
This supersedes #266. I changed verilog files so I want CI to run.
* Renamed header_print_cord_x/y to origin_cord_x/y
* Switched to printing manycore relative x/y coordinates instead of global coordinates for parsers
=> Fix Python Origin Bug

software/spmd/bsg_cuda_lite_runtime/eva_range/Makefile, software/spmd/bsg_cuda_lite_runtime/eva_range/kernel_eva_range.cpp, software/spmd/bsg_cuda_lite_runtime/eva_range/main.c, v/vanilla_bean/hash_function.v
Fixes a bug in EVA => NPA translation for DRAM addresses on designs with power of 2 columns.
=> Vanilla bean hash function fix

testbenches/common/v/bsg_nonsynth_mem_infinite.v, testbenches/common/v/spmd_testbench.v
fixes a bug where infinite memories were constant size regardless of the number of columns
=> size of infinite memories scale down inversely to columns

software/bsg_manycore_lib/bsg_manycore_patch.h, testbenches/common/v/nb_waw_detector.v
There's still a missing link regarding how user would reach intended patch. To resolve that, this pr adds patch to bsg_manycore and updates error message to point user directly to the patch with:
```
Please refer to BSG_FIX_WAW_HAZARD macro in bsg_manycore/software/bsg_manycore_lib/bsg_manycore_patch.h for details.
```
=> More info pointing to WAW patch

software/py/blood_graph.py
Addresses issue #281 .
Adds three options for choosing the timing window of blood graphs:
1. --trace: default, use the first and last trace from the trace file as start and end cycle
2. --stats: if the stats file is given as input, use the first kernel_start and last kernel_end stat --> if given as input, it overrides option 1 and narrows the bloodgraph to the window in which the tiles are actually running the kernel
3. --cycle: custom start/end cycles given by the user which overrides the other two 
Minor restructuring of functions and variables as well.
**Merge with PR # 29 in baseline**
=> Extending blood graph timing window options

v/bsg_manycore_link_sif_tieoff.v
In verilator %- causes compilation to fail. %0 does not. I think this fixes it, with the same functionality?
=> Fixed an VCS-specific format string

v/bsg_manycore.v
Fixed a (Verilator-percieved) issue where a net was driven by both blocking and non-blocking assignments
=> Fix multi-driven (?) net issue

machines/16x8/Makefile.machine.include, machines/4x4/Makefile.machine.include, machines/4x4_dmc/Makefile.machine.include, machines/4x4_gs/Makefile.machine.include, testbenches/common/v/spmd_testbench.v, v/bsg_manycore.v, v/bsg_manycore_hetero_socket.v
Verilator can't infer constant-ness through 2D vectors passed as parameters ([Issue](https://github.com/verilator/verilator/issues/2272)). 
Therefore, I've switched hetero_type_vec_p to a 1-dimensional vector. 
I updated the Makefile.machine.include files. I also removed tabs, and updated the comment describing the vector.
Is there a way to run regression on all the machines in Manycore? Is there one that tests the scatter gather accelerator?
This is the last major blocking issue to compiling Manycore in Verilator.
=> Change hetero_type_vec_p to 1-Dimensional Vector

software/py/blood_graph.py, software/py/vanilla_pc_histogram.py
- Previously the PC histogram would traverse the entire range of possible PC's, possibly from 0x00000000 to 0xffffffff to generate histogram --> very inefficient and painfully slow
- Modified it to only traverse the PC's seen in the vanilla operation trace file
- Updated commentary
- Refactored and added some functions to make the code more modular 
- Got rid of redundant print stats functions 
**Merge with PR # in baseline.**
=> General refactoring of Vanilla PC Histogram

v/vanilla_bean/network_rx.v
This can cause erroneous messages to be printed in Verilator during reset
=> Guard error statement with reset_i

software/py/vanilla_stats_parser.py, software/py/vcache_stall_graph.py, testbenches/common/v/vcache_profiler.v
* Changed vcache profiler to not count missing load/store requests as completed operations (This way, missing requests + hit requests + stall cycles = total cycles)
* Added warning if the vcache_stats.csv or vcache_operation_trace.csv is missing. This way simulation doesn't terminate with errors if it is using infinite_mem (4x4_fast_n_fake)
* Added a not_stall section to the vcache stall stats (% of useful work)
* Added a per-vcache statistics with utilization for the manycore_stats.log 
* Minor bug fixes.
=> Minor refactor of Vcache profiler, stats parser and stall graph

software/README.md, software/mk/Makefile.builddefs, software/mk/Makefile.llvminstall, software/spmd/Makefile, software/spmd/c++/Makefile, software/spmd/c++/main.cpp
Neil built a great flow for compiling and running llvm, including a pass. This PR extends that with the following:
- Cross-compiling with generic LLVM build. So Manycore can work with system LLVM! (Provided, system LLVM is >=9.0.0)
- Ability to use C/C++ standard libraries. 
- Options for compiling with accurate ABI and ISA extensions.
- Option to enable/disable the pass.
- With C/C++ stdlib support, any program using `Makefile.builddefs` can be compiled with LLVM now: just run `make CLANG=1`.
Regression with LLVM: 
- Only three tests fail with Clang enabled: `bsg_tile_group_barrier`  `bypass_core` and `bsg_lr_acq`!!!
- May be an extra setting is required for correct atomic support, or could be a problem with codegen for atomics. Will look into it later, as the current priority is …
=> LLVM cross-compilation

software/mk/Makefile.builddefs
Output text IR at intermediate steps to be able look at and analyze transformation when necessary. This might slow down the compilation a bit which is not a concern when compiling individual or only a handful of device kernels.
=> Output text form of LLVM IR at intermediate steps

software/mk/Makefile.llvminstall, software/riscv-tools/Makefile, software/riscv-tools/README.md
- modified the existing llvm install build file to instead clone our fork of llvm and build with support for our hb specific backend
- our llvm backend is still under development, but I retained the last line of the makefile that deletes the source and build directories - thoughts on whether we should keep or remove that line?
=> modify llvm install script to install our version of llvm

testbenches/dpi/bsg_nonsynth_dpi_manycore.hpp, testbenches/dpi/bsg_nonsynth_dpi_manycore.v
Will document in time - and more examples to follow. 
BUT - a question for discussion. Should the top-level file testbench file live in replicant, or manycore? 
We can actually use the same top-level file for both SPMD loader and CUDA, it's just the C libraries that differ. We'd need a new SPMD loader that uses a C/C++ API but I don't see any major issues there.
=> Added DPI Interface for Manycore

testbenches/common/v/vanilla_core_profiler.v, testbenches/dpi/vanilla_core_profiler.hpp
This DPI interface allows a simulator to read floating point instructions executed, integer arithmetic instructions executed, and total number of instructions executed. 
It works in Verilator and VCS. A corresponding PR (and testbench) will be in bsg_replicant.
=> DPI interface for profiler

software/bsg_manycore_lib/bsg_manycore.h, software/mk/Makefile.builddefs, software/mk/Makefile.llvminstall, software/mk/Makefile.tail_rules
- Added target specific flags to `llc` command, to be safe with future versions of LLVM.
- Added `-fno-fast-math` flag to `float_all_ops` testcase, as this testcase specifically tests FP compliance.
=> Target specific LLVM flags; Utility macros for Clang.

software/spmd/bsg_cuda_lite_runtime/float_all_ops/Makefile, software/spmd/float_cmp/Makefile, software/spmd/float_cmp/main.c
Checks NAN comparison compliance by disabling `-ffast-math` optimizations.
=> Testcase to compare NANs

testbenches/common/v/bsg_manycore_top_crossbar.v
This small change vastly simplifies processing for the DPI hierarchy in C/C++
The remaining differences can be handled in C/C++
=> Small modification to naming and indexing to make hierarchy path more similar to mesh network

testbenches/common/v/bsg_manycore_link_to_cache_tracer.v, testbenches/common/v/infinite_mem_profiler.v, testbenches/common/v/instr_trace.v, testbenches/common/v/vanilla_core_profiler.v, testbenches/common/v/vanilla_core_trace.v, testbenches/common/v/vcache_non_blocking_profiler.v, testbenches/common/v/vcache_profiler.v
Verilator added support for $root, so I took another stab at this. This is the first (and most important?) of the profilers. 
In general: 
- Replaced forever with `always @(negedge clk_i)`
- Replaced `#1` with `always @(my_x_i)` on the assumption that my_x_i and my_y_i only change once
- Fixed an issue where stat_r had both blocking and non-blocking assignments. 
I'm least comfortable with replacing `#1` with `always @(my_x_i)`. It seems like we have to guarantee that `my_y_i` has to change before `my_x_i. @tommydcjung Do you have any ideas here?
Also, apologies. My text editor "fixed" indentation and inserted whitespace. Turn on ignore whitespace changes to see the 30-ish lines I had to change.
=> Fixed Profilers for Verilator

testbenches/common/v/vanilla_core_trace.v, v/bsg_manycore_accel_default.v
The first fix (`testbenches/common/v/vanilla_core_trace.v`) must have gotten dropped in a rebase. 
The second fix is a new issue that has popped up with the new parameter `num_tiles_y_p`
=> Small fixes for Verilator

v/vanilla_bean/scoreboard.v
Area
---------
Before:
proc/h_z/vcore/float_sb             138.3379
proc/h_z/vcore/int_sb               122.4922
After:
proc/h_z/vcore/float_sb             120.6778
proc/h_z/vcore/int_sb               109.4285
Timing
report_timing -through [get_pin proc/h_z/vcore/float_sb/score_i] -through [get_pin proc/h_z/vcore/float_sb/dependency_o]
----------------
Before (262 ps):
proc/h_z/vcore/float_sb/score_i (bsg_manycore_tile_scoreboard_els_p32_num_src_port_p3_num_clear_port_p1_x0_tied_to_zero_p0_0) <-
0.00     393.23 f
proc/h_z/vcore/float_sb/score_demux/v_i (bsg_manycore_tile_bsg_decode_with_v_num_out_p32_1)
0.00     393.23 f
proc/h_z/vcore/float_sb/score_demux/U1/Z (BUFX6)
18.89     412.12 f
proc/h_z/vcore/float_sb/score_demux/U8/Z (CKAN2X1)
23.91     436.03 f …
=> scoreboard critical path

testbenches/common/v/bsg_manycore_top_crossbar.v
Verilator doesn't like when parameters are re-assigned -- for example when initialized to a value, and then a subset are re-written. 
This occurs in the crossbar. I've fixed it.
=> Fix parameter setting indexing for Verilator

testbenches/dpi/bsg_nonsynth_dpi_manycore.v
In VCS, the clock is controlled by the simulator. This means that when the "host" C/C++ wants time to pass in the RTL it must yield to the simulator using a delay statement (or similar). This is how the aws-vcs platform simulates in replicant.
This PR effectively adds a method to "yield" from the host C/C++ into the RTL simulation, until the next clock edge. This allows the Manycore DPI interface to be used with VCS. As a happy result,  the same RTL top level and C/C++ libraries to simulate with both VCS and Verilator tools.
=> Add bsg_dpi_next() to manycore DPI interface to support VCS simulation

software/riscv-tools/Makefile
In our local branch of riscv-gnu-toolchain, in the riscv-gcc submodule, I switched from the master branch to bsg_manycore_gcc (formerly named max-gcc) 
In addition, I also removed the commands that patched riscv-gcc. @vb000 can you confirm that I correctly applied this patch in riscv-gcc? https://github.com/bespoke-silicon-group/riscv-gcc/commit/8d25c1fa02742dac58e96a34704ad4d0262b76e5
=> Switch to BSG GCC in RISC-V Tools

software/bsg_manycore_lib/bsg_tile_group_barrier.hpp
I've added a comment that I think is worth documenting. 
This is something that scared me. I was worried that we were not initializing the barriers before launching a tile. Thankfully, Max knows his C/C++ and ELF files and handled this last year.
However, the process of confirming this comment took a few days, and a meeting with Max. I've added a comment to avoid anyone performing the same traversal.
=> Added a comment that describes barrier initialization

software/py/bsg_manycore_link_gen.py
The new linker script generator globs everything left during linking, into .dram. This includes debug symbols. 
This PR fixes that, by removing .* from .dram. This re-enables the ability to print in-line sources during disassembly. 
With the current solution the debug symbols are ALL loaded into the simulation during execution. This signficantly slows down runtime for large kernels when debug symbols are compiled.
If there's a better fix, I'm all ears. This is a high-priority needs-to-be-fixed for me.
=> Removed .* matching from .dram section in link gen

software/riscv-tools/Makefile, software/riscv-tools/spike-gcc.patch
Creates a patch to add stdexport imports to riscv-isa-sim that are needed for gcc10. It's the same fix as this issue here...
riscv/riscv-isa-sim#459
=> Fix for compiling riscv-isa-sim with GCC10

software/bsg_manycore_lib/bsg_manycore.h, software/spmd/nbloads/Makefile, software/spmd/nbloads/main.c, software/spmd/nbloads/vec_add.c, software/spmd/nbloads/vec_sub.cpp
Update non-blocking loads related macros with bsg prefixes:
- `__remote` --> `bsg_attr_remote`
- `NOALIAS` --> `bsg_attr_noalias`
- `UNROLL` --> `bsg_unroll`
Tested on pytorch regression.
=> Added bsg prefixes to non-blocking load related macros

software/mk/Makefile.master
This is the distro independent way of calling unix utility functions
https://en.wikipedia.org/wiki/Env
Related, but does not solve https://github.com/bespoke-silicon-group/bsg_manycore/issues/392
=> Switch instances of /bin to env in Makefiles

testbenches/common/v/vcache_profiler.v
* Atomic Miss (miss_amo)
* Response Network Stall (stall_rsp)
Atomic misses will be useful for @eafurst when measuring the performance of of graph applications that use an atomic hash table. 
Response network stalls might give insight into pathological performance
=> Added cache operations that were previously uncounted

Makefile, software/spmd/Makefile.include
Had issues with ubuntu using Dash instead of Bash as the default shell. This fixes that and also makes perl invocation generic. 
This addresses issue #425
=> More fixup for ubuntu

software/py/vanilla_parser/pc_histogram.py
Small profiler fix
This happens when a kernel does not fully occupy every available tile and some tiles do not have any pc_lists
If pc_list is empty the profiler crashes. now it can silently continue to another tile
=> Check for empty tile pc_list when building pc_histogram

software/mk/Makefile.llvminstall
This has been irritating for a while. On the ZeBu system I've been iterating on they only provide cmake, not cmake3, and I can't symlink. 
This solution attempts to find the cmake3 binary (standard only in RHEL), then the cmake binary, and fails (appropriately) if it can find either.
=> Added LLVM Makefile commands to try for cmake3

machines/sim_filelist.mk, testbenches/common/v/remote_load_trace.v, testbenches/common/v/spmd_testbench.v
example output
```
start_cycle,end_cycle,src_x,src_y,dest_x,dest_y,type,latency
25059,25069,0,2,1,0,icache,10
25074,25084,0,2,1,0,icache,10
25089,25099,0,2,1,0,icache,10
25104,25114,0,2,1,0,icache,10
25119,25129,0,2,1,0,icache,10
25133,25145,0,2,2,0,int,12
25134,25146,0,2,2,0,icache,12
25151,25163,0,2,2,0,icache,12
25168,25180,0,2,2,0,icache,12
25185,25197,0,2,2,0,icache,12
25202,25214,0,2,2,0,int,12
25219,25231,0,2,2,0,int,12
25236,25248,0,2,2,0,int,12
25255,25267,0,2,2,0,icache,12
25272,25284,0,2,2,0,icache,12
```
=> remote_load_trace

machines/arch_filelist.mk, machines/sim_filelist.mk
* Also in sim_filelist.mk, which is not used in Repliant.
I think this is independent of #448?
=> Added missing file to arch_filelist.mk

v/bsg_manycore_hor_io_router.v
Hasn't been functionally tested, but it synthesizes out the unnecessary crossbar directions
Dunno why it won't me reopen #455 ...
=> Tieing off unnecessary ruche link ports on io router

v/bsg_cache_dma_to_wormhole.v
Adding two FIFO for returning wormhole link, so that endpoint is "input-buffered", also to mitigate long timing paths.
=> Bigblade wh return fifo

software/py/vanilla_parser/stats_parser.py
Depends on #426 
The original parser had a few bugs, at least one of which was fundamental. This PR solves this and adds a few new features
New Features:
1. Atomic Miss Counting
2. Response Network Congestion counting
3. Memory access latency
4. Field documentation (see examples below)
Bug Description: 
1. Order of operations (this was in #417)
2. Multiple start/end calls with the same tag (A temporary fix was in #417)
3. Perceived ordering of Start/End relative to tile program order
The original parser was written so that only the first (ever, within a simulation run) and last (ever, within a simulation run) statistics for a given (tag, group) were counted. This ignores that a (tag, group) may have a loop in it, and cause start/end to be called multiple times. If this happens, then the …
=> Rewrite Victim Cache Profiler Parser

software/py/vanilla_parser/stats_parser.py
When using multiple tags the previous code was not correctly calculating the start/min cycle for each tag.
This PR instead initializes `manycore_cycle_parallel_earliest_start` to be the maximum event found in `traces` so that each tag is able to find the minimum event/cycle associated with that tag. 
These values are then updated in lines 1437/1438 and 1474/1475 to the minimum cycle.
=> quick fix for abs cycle count with mult. tags

software/bsg_manycore_lib/bsg_manycore_atomic.h, software/spmd/amoadd_test/Makefile, software/spmd/amoadd_test/main.c, software/spmd/vcache_atomics/main.c, v/bsg_manycore_link_to_cache.v, v/bsg_manycore_tile_vcache.v, v/vanilla_bean/bsg_vanilla_pkg.v, v/vanilla_bean/cl_decode.v, v/vanilla_bean/network_tx.v
The manycore currently supports only AMOSWAP and AMOOR operations. This PR adds AMOADD support as well. 
Correspondly macros for software use in `bsg_manycore_atomic.h` have been added, an update to the `vcache_atomics` test and a multicore test exercising the use of atomic adds.
=> Atomic Add support 

testbenches/common/v/bsg_nonsynth_manycore_testbench.v
Adds the two ports to the DRAMSim3 Module instantiation. Uses $root to pull from the top level, so this solution works for both spmd_loader, and replicant.
Merge after https://github.com/bespoke-silicon-group/basejump_stl/pull/367
=> Added print_stat wires to DRAMSim3

testbenches/common/v/bsg_nonsynth_manycore_testbench.v, v/bsg_manycore_pod_ruche.v, v/bsg_manycore_pod_ruche_array.v
As title describes, pulled this out for network simulation and as a feature request by Cornell.
When the pod is split into two X and two Y subarrays, this is printed out: 
```
```
(NB: 9 is the type for my DPI tile. I also tested with 0.)
=> Pulled hetero_type_vec to top level of common testbench

v/bsg_manycore_link_to_cache.v
* e_remote_store can be used to clear a tag, e_remote_sw cannot. This
fixes the issue
Don't merge yet, I still need to understand why this isn't showing up in our regression in replicant, but is in PyTorch
=> Add e_remote_sw to link_to_cache case statement

v/bsg_manycore_link_sif_tieoff.v
Direct assignments to structs of type packed logic are nonsynthesizable. In simulation, this results in Xs.
=> Fix nonsynth code in bsg_manycore_link_sif_tieoff

machines/arch_filelist.mk, v/bsg_manycore_endpoint_fc.v, v/bsg_manycore_endpoint_standard.v
Context from Slack:
> Hey all, Dustin and I just met to discuss unifying BlackParrot and x86 host interface hardware a bit more.  One thing we've noticed is that endpoint standard essentially does 3 things over regular endpoint: flow control, the extra features like locking, and simplifying the I/O ports from mc_packet to individual fields. For host interfaces, we are interested in the flow control, but not the rest. In fact, we wish to speak packet directly because that's roughly what the host speaks. Otherwise, we end up having to reconvert from the output of endpoint standard back into bsg_manycore_pkt_s which is tedious and error-prone.
> We propose refactoring a middle endpoint module, bsg_manycore_endpoint_fc, such that bsg_manycore_endpoint_standard wraps bsg_manycore_endpoint_fc …
=> Adding bsg_manycore_endpoint_fc

testbenches/common/v/bsg_nonsynth_manycore_io_complex.v
In order to verbose in tapeout testbench
=> Expose spmd_loader verbose_p outside io_complex

software/bsg_manycore_lib/bsg_manycore.h, software/spmd/beebs/Makefile, testbenches/common/v/bsg_nonsynth_manycore_monitor.v, v/bsg_manycore_addr_pkg.v
* Added start/iter/end heartbeat macros
* Updated submodule to new branch
I added three macros for a heartbeat. I figured most code would have initialization code, and some might have checking code at the end. Since errors can still happen in these regions, I wanted to provide a way to annotate setup and teardown code.
I also wanted this to be reusable and light weight, hence why i added it to manycore and not just adding a bsg_printf macro.
Example output:
```
[BSG_INFO][SPMD_LOADER] SPMD loader finished loading. t=10619000
[INFO][RX] Unfreezing tile t=10622000, x= 16, y=  8
[INFO][MONITOR] RECEIVED HEARTBEAT START from tile y,x= 8,16, data=00000000, time=489063000
[INFO][MONITOR] RECEIVED HEARTBEAT ITER from tile y,x= 8,16, data=00000000, time=508000000
[INFO][MONITOR] RECEIVED …
```
=> Add heartbeat to beebs, and macros and definitions for reuse

software/spmd/quicksort/main.c, software/spmd/quicksort_by4/Makefile, software/spmd/quicksort_by4/main.c
* Add _by4 variant with 4x less data
* Remove bsg_printf when passes
Quicksort is one of the longest (if not _the_ longest) running tests when we move to full-chip simulation. I added a variant that uses 4x less data and runs about 5x faster. This doesn't supersede quicksort, it just adds a faux-heartbeat. 
I also removed the printf when the tests passes.
=> Shorter quicksort Variant

software/spmd/Makefile, software/spmd/amoadd_test/main.c, software/spmd/bsg_outbuf_full2/main.c, software/spmd/perf_test_conv3x3/main.cpp, software/spmd/perf_test_reduction/main.cpp, software/spmd/vcache_atomic_inc/main.c, testbenches/common/v/bsg_nonsynth_manycore_spmd_loader.v
* Replace printf with bsg_print_hexadecimal/int or heartbeats
* make SPMD loader print once every 1024 packets when !verbose_p
In the RC-ALPHA-RTLFREEZE-0 RTL the following tests were the longest of the SPMD suite: 
* quicksort 12961 sec
* vcache_atomic_histogram 17486 sec
* vcache_atomic_histogram2 17739 sec
* perf_test_reduction 20072 sec
* perf_test_conv3x3 21529 sec
* test_credit_limit_csr_multi 22100 sec
* amoadd_test 24099 sec
* bsg_barrier 24771 sec
* bsg_tile_group_barrier 26798 sec
* jal_rv32 28044 sec
* vcache_atomic_inc 28875 sec
* bsg_outbuf_full2 42535 sec
Of these, quicksort (fixed in #530), perf_test_reduction, perf_test_conv3x3, amoadd_test, bsg_barrier, bsg_tile_group_barrier, vcache_atomic_inc, bsg_outbuf_full2 use bsg_printf. Most of these can be replaced with …
=> Reducing runtime of simulation execution

testbenches/common/v/bsg_nonsynth_mem_infinite.v
Quick fix to bsg_nonsynth_mem_infinite for endpoint change
=> Fix bsg_nonsynth_mem_infinite.v

software/py/nbf.py
Fixing excessive runtime of nbf.py
=> call get_spmd_binary_size only once

testbenches/dpi/bsg_nonsynth_dpi_manycore.v, v/bsg_manycore_accel_default.v, v/bsg_manycore_gather_scatter.v, v/bsg_manycore_vcache_blocking.v
This PR fixes the compilation for manycore hetero accelerators. This is necessary for verilator compilation because it compiles files which are unused (which is why VCS doesn't pick up this breakage: a good reason to run Verilator in CI, but I digress).
Are there any hetero machine configs / programs to test this on? I would like to make sure the functionality is there, but if there's nothing available, we should settle for fixing the compilation.
=> Fixing up manycore accelerators

software/bsg_manycore_lib/bsg_manycore.h, software/spmd/Makefile, software/spmd/pc_profiler/Makefile, software/spmd/pc_profiler/README.md, software/spmd/pc_profiler/main.c, software/spmd/pc_profiler/profiler.S
This PR adds a software-based PC Profiler that uses the trace interrupt handler to build a PC histogram in DRAM.
There are 2 main files - 
1. profiler.S --> This is a C runtime file that does most of the initialization but in addition has the trace interrupt handler defined that updates the histogram. The profiler (i.e trace interrupt handler) uses the first 2 entries in DMEM to spill any registers before performing any action. It computes the index into the histogram based on the EPC and then atomically increments that location in memory. This depends on #476 to work correctly. Each PC has a 4 byte bin assigned to it at HISTOGRAM_BASE_ADDR + EPC.
2. main.c --> This contains a C program that sets up the tile and computes the first 10 fibonacci numbers (just a sample, could ideally be …
=> PC Profiler

testbenches/common/v/vanilla_core_profiler.v
Didn't print stats because tag coordinates did not match with check.
=> fix vcore profiler

software/py/vanilla_parser/common.py, software/py/vanilla_parser/stats_parser.py
While thinking through performance optimization on the manycore we realized it is critical to have a few more metrics on the memory system.
This PR will probably include a few other updates, too (DRAM BW metrics, etc)
First: A metric for how much of a cache line is being used before it is evicted. At the moment I am computing a bytes loaded At the moment these are called Bytes Used Ratios, but I'm open to naming suggestions. 
Before: 
```
-----------------------------------------------------------------------------
Miss Statistics                                                              
-----------------------------------------------------------------------------
Type       Misses    Accesses    Miss Rate (%)
-------  --------  ----------  ---------------
Stores          0 …
```
=> Add new cache statistics 

software/py/nbf.py
vcache_wh_dest should be set for every vcache in the pod array, whether or not that its pod have tiles being launched.
=> setting vcache_wh_dest for all pods

.gitlab-ci.yml, machines/platform.mk, software/spmd/bsg_simple_mutex_test/Makefile
Adding pod_4x4_hbm2 CI and reducing bsg_simple_mutex_test iteration times, which takes the longest time to run.
=> Ci pod 4x4 hbm2

software/spmd/credit_pkt_regfile_corrupt_test/Makefile, software/spmd/credit_pkt_regfile_corrupt_test/main.S
This test recreates the bug where a residual credit pkt in the return FIFO corrupts the regfile state.
=> Credit pkt regifile corrupt test

software/bsg_manycore_lib/bsg_group_strider.hpp, software/spmd/strider/Makefile, software/spmd/strider/main.cpp
This is a C++ class for striding between tiles in a tile group.
It can be used to stride between tiles in the horizontal, vertical, or diagonal direction. This can be more than the size of the tile group, but must be static.
This is used in the optimized SGEMM implementation, but is more general than that. Hence, why it is being merged here.
=> Add bsg_group_strider, and SPMD test

machines/sim_filelist.mk, testbenches/common/v/profiler.hpp, testbenches/common/v/profiler.vh, testbenches/common/v/remote_load_profiler.cpp, testbenches/common/v/remote_load_trace.v, testbenches/common/v/spmd_testbench.v, testbenches/common/v/vanilla_core_profiler.cpp, testbenches/common/v/vanilla_core_profiler.v, testbenches/common/v/vcache_profiler.cpp, testbenches/common/v/vcache_profiler.v
Currently the tracers call $fopen and $fclose inside of always blocks in modules that are instantiated many times.
When the trace is enabled this results in $fopen/$fclose being called redundantly many times per cycle.
I found that calling $fopen and $fclose just once at the start of the simulation reduced sim time by 1.6x (average) and as much as 2x.
=> Moves File Open/Close Operations in Trace Profiler

testbenches/common/v/profiler.vh, v/bsg_manycore_accel_default.v, v/bsg_manycore_gather_scatter.v
These are minor fixes to get verilator back and happy. The barrier change is just to stifle errors since those modules are unused and probably broken as is. The profiler change is to get around a feature missing of declaring a local int variable within an initial/final block.
Merge with: https://github.com/bespoke-silicon-group/bsg_replicant/pull/752
=> Refix verilator

software/bsg_manycore_lib/bsg_manycore.h
I understand why the existing macros are used, and why Tommy is using packets, not architecturally-idempotent operations (like these)
Brining these back temporarily to evaluate both approaches.
=> Add nonsynth saifgen macros

testbenches/common/v/bsg_nonsynth_manycore_testbench.v, testbenches/common/v/spmd_testbench.v
This seems like a simple fix, but I want to make sure we're all on board because it has some subtle (and annoying) implications.
There are two changes. First, because Verilator doesn't correctly handle parameter-controlled instantiation of modules, our methodology for disabling/enabling the profilers doesn't work in Verilator. Instead, we need to "clock gate" them like so: 
```   
bind vanilla_core vanilla_core_profiler #(
.x_cord_width_p(x_cord_width_p)
,.y_cord_width_p(y_cord_width_p)
,.icache_tag_width_p(icache_tag_width_p)
,.icache_entries_p(icache_entries_p)
,.data_width_p(data_width_p)
,.origin_x_cord_p(`BSG_MACHINE_ORIGIN_X_CORD)
,.origin_y_cord_p(`BSG_MACHINE_ORIGIN_Y_CORD)
) vcore_prof (
.*
,.clk_i(clk_i && $root.`HOST_MODULE_PATH.testbench.enable_vcore_profiling_p)
```
I added a …
=> Added a workaround for parameter-controlled elaboration in Verilator

testbenches/common/v/vanilla_core_profiler.v
Fixing the bug discovered by @yodada, where int_sb_r/float_sb_r is not resetting correctly in profiler, which leads to mis-categorization of stall_depend_long_op.
=> [vanilla_core_profiler] Fixing int_sb_r/float_sb_r not resetting correctly in profiler

software/bsg_manycore_lib/bsg_manycore.h
Admittedly one of the more odd PRs that I've submitted.
This PR adds two inline functions: `bsg_amo_prefetch` and `bsg_lw_prefetch`. These functions can be used to prefetch data into the cache for a tile to read later.
`bsg_amo_prefetch` uses `amoor.w`, but with an operand of 0 so it doesn't disturb data. However, the cache doesn't know this so it pollutes the dirty bit. Therefore, `bsg_amo_prefetch` should only be used to verify prefetching behavior. In the statistics parser, correct use of `bsg_amo_prefetch` will drive the load/store miss rate to 0
After verifying behavior with `bsg_amo_prefetch` replace all instances with `bsg_lw_prefetch`
* bsg_amo_prefetch and bsg_lw_prefetch both target x0 to avoid architectural dependencies
* Use amo to verify behavioral functionality of preloads, …
=> Add amoor and lw prefetch commands

software/py/pc_histogram.py
Added a few new (useful) flags to the PC/BB histogram tool
0. Allow users to specify --start/end as shorter hex values, and interpret as int
1. Added `--without` argument. `--without` allows users to specify which PC to filter out. If a PC is specified, the entire BB that contains the PC is removed from the BB histogram. Users can specify `--without` multiple times, e.g. `--without 0x200 --without 0x300`
=> PC Histogram Enhancements

software/py/remote_prof.py
This python script parses remote_load_trace.csv. It produces three outputs: 
`request_heatmap.pdf`: A heatmap showing cache bandwidth utilization of LOAD and STORE requests issued to each cache within a series of time windows (bins). The bandwidth utilization is shown as a percent in the heatmap so that heatmaps can be compared.
`meanlat_heatmap.pdf`: A heatmap showing mean latency of all LOADS issued to each cache within a series of time windows (bins).
`maxnlat_heatmap.pdf`: A heatmap showing mean latency of all LOADS issued to each cache within a series of time windows (bins).
Examples are attached.
```
usage: remote_prof.py [-h] [-s SOURCE] [--first FIRST] [--last LAST]
[--cycbin CYCBIN] [--nbins NBINS] [--filename FILENAME]
Argument parser for the HB Spacetime Heatmap (Remote Load …
```
=> Spacetime Heatmap

v/vanilla_bean/regfile_synth.v
This PR resolves the regfile mapping problem on the Ultrascale Plus FPGA. currently regfile is mapped as registers instead of LUTRAMs. The mapping problem can be resolved by unpacking the arrays and tweaking the combinational logics.
1. It is functionally identical to the original version (verified with randomly-generated testbench in both VCS and Vivado simulators)
2. ASIC resource utilization change is minimal (-0.1% area) after synthesis in DC
3. LUT utilization on FPGA reduce by 15% in Vivado
=> Update regfile_synth for ultrascale plus fpga mapping

README.md, machines/Makefile.vcs, machines/Makefile.xcelium
This PR extends a guard for bsg_cadenv (IGNORE_CADENV) to other files. It's useful for building with verilator without bsg_cadenv existing at all. It also describes the flow in a bit more detail for users unfamiliar with git
This goes after #662
=> Cadenv fix

v/vanilla_bean/fpu_fdiv_fsqrt.v, v/vanilla_bean/idiv.v, v/vanilla_bean/vanilla_core.v
The following modules have ready signals that closely follow the rv->& paradigm of handshakes, and have been updated to more accurately represent that as per the coding standards guide for clarity.
=> Updates ready naming conventions for vanilla bean

machines/xcelium_dump.tcl, testbenches/common/v/bsg_nonsynth_manycore_testbench.v, testbenches/common/v/spmd_testbench.v, testbenches/common/v/vanilla_core_saif_dumper.v
https://github.com/bespoke-silicon-group/bsg_manycore/blob/8b450d997095c84dbfe5a44b83c7ea00713025b3/testbenches/common/v/bsg_nonsynth_manycore_testbench.v#L168
This path broke as a result of this change: #652
=> Fix host module paths in saif dumper

testbenches/common/v/vanilla_core_profiler.v, testbenches/common/v/vanilla_exe_bubble_classifier.v, testbenches/common/v/vanilla_exe_bubble_classifier_pkg.v, testbenches/common/v/vanilla_scoreboard_tracker.v, testbenches/common/v/vanilla_scoreboard_tracker_pkg.v
- Adding the counter whether the dram access was sequential (consecutive access based on the same rs1) vs non-sequential.
- Splitting stall_depend_dram_load into atomics, sequential loads, non-sequential loads.
=> [profiler] Dram Stall stats

software/py/vanilla_parser/blood_graph.py
Adding dram stall type to blood graph, fixes:  https://github.com/bespoke-silicon-group/bsg_manycore/pull/694/files 
Not committed to the color, just picked something
=> Adding dram stall type to blood graph

software/mk/Makefile.verilog
This allows one to use bsg_cadenv on machines hosted in other domains (or Docker images). Should have no new behavior on current setups. It also has the advantage of alerting bsg users if they forget to clone bsg_cadenv alongside of bsg_manycore
=> Updating hostname detection to be bsg_cadenv detection

software/mk/Makefile.builddefs
Old versions of bash do not like |&. 2>&1 has the same functionality but greater compatibility: https://stackoverflow.com/questions/20553916/syntax-error-near-unexpected-token-using
=> Change pipe structure for bash compatibility

testbenches/common/v/vcache_profiler.v
miss is being double-counted with load/store, when the miss completes and when v_o is high.
=> [vcache_profiler] Fix inc_miss double-counting

machines/arch_filelist.mk
This PR bumps to latest hardfloat, which is needed for a minor filename change (bsg_hardfloat_pkg.v->.sv) and a minor synthesis issue with wire vs logic.
=> Bump to latest hardfloat

v/bsg_manycore_accel_default.sv
The current order makes rev_fifo_els_p and fwd_fifo_els_p localparam instead of param, which makes them technically non-overrideable. VCS ignores this, but verilator does not
=> Fixing order of localparam in bsg_manycore_accel_default

software/mk/Makefile.builddefs, software/py/bsg_manycore_link_gen.py
- Adding a flag --move_rodata_to_dmem.
- By default, this flag is turned off.
=> Adding a flag to linker gen script to move rodata to dmem;

software/riscv-tools/Makefile
recent versions of configure error out on relative --prefix
=> Hotfix: depends path in makefile

software/riscv-tools/Makefile
The Makefile currently uses &> which works in bash, but not other shells. On Ubuntu 20.04.6 LTS, `make` uses /bin/sh, which is a symlink to dash. dash does not support this syntax.
This PR explicitly sets the shell to bash in the Makefile.
Issue reported in https://github.com/black-parrot-hdk/zynq-parrot/issues/106.
=> Use bash shell in riscv-tools Makefile

testbenches/common/v/mini_testbench.sv, v/miniblade/bsg_miniblade_pod.sv
Adding global_x/y_i ports to the pod module;
So that coordinates are injected at the top-level, and avoid creating extra space above IO router tiles to place tieoff cells;
=> adding global_xy_i ports

software/bsg_manycore_lib/bsg_cuda_lite_barrier.h
Before this fix: if a cuda kernel invokes the barrier an odd number of times when using the amoadd barrier, then a second kernel launch will hang since barrier is always initialized to zero by the host.
After this fix: the sense is initialized to 1 and the barrier is set to 0.
=> Sets sense to 1 in init for amoadd barrier

software/mk/Makefile.llvminstall
Allow llvm installation with gcc11. This would be useful for OS that does not support devtoolset-8 (like Rocky 9 with gcc11 as default)
Tested with gcc 9.3.1, 10.2.1, 11.2.1 and 11.5.0 (llvm installation finished)
=> Allow llvm installation with gcc11
