bespoke-silicon-group/bsg_manycore

software/spmd/bsg_cuda_lite_runtime/Makefile, software/spmd/bsg_cuda_lite_runtime/graph_degree_count.c
* This adds a test case that I've been working on.
=> Bladerunner v030 cuda graph test

software/spmd/fft/main.c
Made `spmd/fft` into a working FFT benchmark
=> FFT application

software/spmd/bsg_loader_suite/Makefile, software/spmd/bsg_loader_suite/Makefile.common, software/spmd/bsg_loader_suite/loopback/Makefile, software/spmd/bsg_loader_suite/loopback/main.c, software/spmd/bsg_loader_suite/loopback_big_text/Makefile, software/spmd/bsg_loader_suite/loopback_big_text/main.c, software/spmd/bsg_loader_suite/loopback_cache/Makefile, software/spmd/bsg_loader_suite/loopback_cache/main.c, software/spmd/bsg_loader_suite/loopback_fail/Makefile, software/spmd/bsg_loader_suite/loopback_fail/main.c
This starts a test suite to exercise our F1 loader.
=> adds a spmd test suite for our host loader

software/spmd/bsg_loader_suite/Makefile, software/spmd/bsg_loader_suite/npa_to_eva/Makefile, software/spmd/bsg_loader_suite/npa_to_eva/main.c, software/spmd/symbol_to_eva/Makefile, software/spmd/symbol_to_eva/main.c
* test that writes an EVA
* test that exists just to exercise `symbol_to_eva`
=> More test programs for EVA Functions

software/bsg_manycore_lib/bsg_manycore_arch.h, software/mk/Makefile.filelist, software/mk/Makefile.verilog, software/spmd/bsg_riscv_tests/Makefile, software/spmd/crc32/main.c, software/spmd/fib/main.c, software/spmd/hello/Makefile, software/spmd/quicksort/main.c, testbenches/basic/test_bsg_manycore.v, testbenches/common/v/bsg_manycore_axi_mem.v, testbenches/common/v/bsg_manycore_proc_vanilla_trace.v, testbenches/common/v/bsg_manycore_spmd_loader.v, testbenches/common/v/bsg_manycore_tile_trace.v, testbenches/common/v/bsg_nonsynth_manycore_io_complex.v, v/bladerunner/bsg_manycore_wrapper.v, v/vanilla_bean/bsg_manycore_proc_vanilla.v, v/vanilla_bean/definitions.vh, v/vanilla_bean/hobbit.v, v/vanilla_bean/load_packer.v, v/vanilla_bean/parameters.vh
Merging some remaining changes from dev before closing it
* Added trace functionality
* Moved Host Interface to (0,0)
* Set Tile Group size to 1x1 for RISC-V ISA Tests
To make this PR I rebased dev onto master and squashed information-less commits that had messages like "temp commit". In the future, please make your commit messages more informative.
=> PR Dev to Master

software/bsg_manycore_lib/bsg_cuda_lite_runtime.h
Band aid fix that gets the CUDA API working again, but the whole process showed the potential for a serious bug (issue #175 in bsg_f1), to be fixed. Please merge ASAP.
=> Hotfix! Bug fix for new PR.

software/spmd/bsg_cuda_lite_runtime/multiple_binary_load/Makefile, software/spmd/bsg_cuda_lite_runtime/multiple_binary_load/kernel_empty.c, software/spmd/bsg_cuda_lite_runtime/multiple_binary_load/main.c
Related to issue # 300 on bsg_f1.
=> Added a new cuda lite runtime regression test initialize, load binary, run and finish twice

v/bsg_manycore.v, v/bsg_manycore_link_async_to_wormhole.v
Adding pipeline reset depth parameters to bsg_manycore and bsg_manycore_link_async_to_wormhole. Adding reset register fanout to all tiles inside of bsg_manycore.
=> Pipelined reset parameters and reset register fanout.

software/spmd/bsg_cuda_lite_runtime/dram_device_allocated/Makefile, software/spmd/bsg_cuda_lite_runtime/dram_device_allocated/kernel_dram_device_allocated.c, software/spmd/bsg_cuda_lite_runtime/dram_device_allocated/main.c, software/spmd/bsg_cuda_lite_runtime/dram_host_allocated/Makefile, software/spmd/bsg_cuda_lite_runtime/dram_host_allocated/kernel_dram_host_allocated.c, software/spmd/bsg_cuda_lite_runtime/dram_host_allocated/main.c, software/spmd/bsg_cuda_lite_runtime/dram_load_store/Makefile, software/spmd/bsg_cuda_lite_runtime/dram_load_store/kernel_dram_load_store.c, software/spmd/bsg_cuda_lite_runtime/dram_load_store/main.c
Added three new cuda lite runtime dram regression tests.
Related to PR # 336 in bsg_f1.
=> CUDA Lite runtime dram regression tests refactored

software/spmd/bsg_scalar_print/Makefile, software/spmd/bsg_scalar_print/main.c
Related to PR # 347 in bsg_f1.
=> Adds a spmd regression test to check the scalar printing functionalities.

software/spmd/bsg_cuda_lite_runtime/float_vec_add/Makefile, software/spmd/bsg_cuda_lite_runtime/float_vec_add/kernel_float_vec_add.c, software/spmd/bsg_cuda_lite_runtime/float_vec_add/main.c
Related to PR # 332 in bsg_f1.
=> Added cuda lite runtime floating point vector addition regression test

software/spmd/bsg_cuda_lite_runtime/max_pool2d/Makefile, software/spmd/bsg_cuda_lite_runtime/max_pool2d/kernel_max_pool2d.c, software/spmd/bsg_cuda_lite_runtime/max_pool2d/main.c
Related to PR # 358 in bsg_f1.
=> Added a cuda lite runtime max_pool2d regression test.

software/riscv-tools/Makefile
Forgot to include this commit in the previous pull request.
=> Fixed parallel build-all

software/mk/Makefile.builddefs, software/mk/Makefile.tail_rules, software/py/post_process_trace.py, testbenches/common/v/bsg_manycore_axi_mem.v
Script to post process cycle-accurate HW trace to generate more human-friendly instruction by instruction execution trace.
This script takes the HW trace like this:
```
56900  0  1: BUBBLE                                       | FP_BUBBLE                      |                              | 
56920  0  1: BUBBLE                                       | FP_BUBBLE                      |                              | 
56940  0  1: BUBBLE                                       | FP_BUBBLE                      |                              | 
56960  0  1: BUBBLE                                       | FP_BUBBLE                      |                              | 
56980  0  1: 00001290 11c000ef x01=00001294               | FP_BUBBLE                      | bt=00000124                  | 
57000 …
```
=> Post process trace

software/bsg_manycore_lib/bsg_newlib_intf.c, software/mk/Makefile.builddefs, software/riscv-tools/Makefile, software/spmd/common/crt.S, software/spmd/common/link_dmem.ld, software/spmd/common/link_dmem2.ld, software/spmd/common/link_dram.ld, software/spmd/common/link_dram2.ld, software/spmd/common/spike.ld
Changed bsg_newlib name to dramfs. Reflecting that change here.
=> Changed bsg_newlib to dramfs

software/spmd/bsg_cuda_lite_runtime/barrier/Makefile, software/spmd/bsg_cuda_lite_runtime/dram_device_allocated/Makefile, software/spmd/bsg_cuda_lite_runtime/dram_host_allocated/Makefile, software/spmd/bsg_cuda_lite_runtime/dram_load_store/Makefile, software/spmd/bsg_cuda_lite_runtime/empty/Makefile, software/spmd/bsg_cuda_lite_runtime/empty_parallel/Makefile, software/spmd/bsg_cuda_lite_runtime/float_vec_add/Makefile, software/spmd/bsg_cuda_lite_runtime/float_vec_add_shared_mem/Makefile, software/spmd/bsg_cuda_lite_runtime/matrix_mul/Makefile, software/spmd/bsg_cuda_lite_runtime/matrix_mul_shared_mem/Makefile, software/spmd/bsg_cuda_lite_runtime/max_pool2d/Makefile, software/spmd/bsg_cuda_lite_runtime/memset/Makefile, software/spmd/bsg_cuda_lite_runtime/multiple_binary_load/Makefile, software/spmd/bsg_cuda_lite_runtime/scalar_print/Makefile, software/spmd/bsg_cuda_lite_runtime/shared_mem/Makefile, software/spmd/bsg_cuda_lite_runtime/shared_mem_load_store/Makefile, software/spmd/bsg_cuda_lite_runtime/stack_load/Makefile, software/spmd/bsg_cuda_lite_runtime/tile_info/Makefile, software/spmd/bsg_cuda_lite_runtime/vec_add/Makefile, software/spmd/bsg_cuda_lite_runtime/vec_add_parallel/Makefile, software/spmd/bsg_cuda_lite_runtime/vec_add_parallel_multi_grid/Makefile, software/spmd/bsg_cuda_lite_runtime/vec_add_serial_multi_grid/Makefile, software/spmd/bsg_cuda_lite_runtime/vec_add_shared_mem/Makefile
=> Removed obsolete lines from bsg_cuda_lite_runtime Makefiles

testbenches/common/v/vanilla_core_profiler.v
These comments explain how to gather the statistics requested in #170
=> added some comments in vanilla_core_profiler

.gitlab-ci.yml, README.md, ci/regress.sh, software/spmd/Makefile
**Outline**:
This flow does following things on every commit to master and any branch named starting with `ci_`:
- Builds toolchain (riscv-gcc and llvm) whenever something in `software/spmd/riscv-tools` is changed.
- Runs SPMD regression.
- Provides a way to manually run cosim regression, which is not currently working because aws-fpga repo is cloned using ssh url. But this should be easy to fix I believe.
**Suggested usage**:  
If you're developing on a branch called `mybranch`, please create a new branch called `ci_mybranch` based on `mybranch` to run CI and `mybranch`. You could keep working on `mybranch` for incremental updates and rebase `ci_mybranch` on `mybranch` when it's ready for another CI run.
**Improvements**:
Tweaking the flow is as easy as modifying any bash script. …
=> Manycore CI on master & branches starting with ci_

software/py/vanilla_stats_parser.py, testbenches/common/v/vanilla_core_profiler.v
Profiler changes for Manycore Atomics
=> Amo profiler

software/bsg_manycore_lib/bsg_manycore.h, software/py/blood_graph.py, software/py/vanilla_pc_histogram.py, software/py/vanilla_stats_parser.py, testbenches/common/v/vanilla_core_profiler.v
I've taken a few liberties with the parser
* Updated formatting, and (hopefully) made it clearer
* Fixed an issue where Tag 0 conflicts with kernel start/end
=> Updated Stats Parser (WIP)

software/spmd/bsg_cuda_lite_runtime/conv2d/Makefile, software/spmd/bsg_cuda_lite_runtime/conv2d/kernel_conv2d.c, software/spmd/bsg_cuda_lite_runtime/conv2d/main.c
See https://github.com/bespoke-silicon-group/bsg_f1/pull/481 for corresponding test
=> Added conv2d kernel

software/py/vanilla_stats_parser.py
* Calling a tag multiple times only reported the final start/end counts for a tile
=> Fixed parser bug

machines/sim_filelist.mk, software/spmd/bsg_cuda_lite_runtime/hammer_cache/Makefile, software/spmd/bsg_cuda_lite_runtime/hammer_cache/kernel_hammer_cache.c, software/spmd/bsg_cuda_lite_runtime/hammer_cache/main.c, testbenches/common/v/bsg_nonsynth_mem_infinite.v, testbenches/common/v/infinite_mem_profiler.v, testbenches/common/v/spmd_testbench.v
* adds backdoor data store to infinite memory module
* infinite_mem_profiler takes a parameter for its log file name
=> Infmem dma

software/py/blood_graph.py, software/py/vanilla_stats_parser.py, software/py/vcache_stall_graph.py, testbenches/common/v/spmd_testbench.v, testbenches/common/v/vcache_profiler.v
Adds stats parser and stall graph for blocking victim cache 
Major changes to vnialla_stats_parser to also include vcache stats
Merge with PR # 543 in bsg_replicant.
=> Blocking VCache stall graph and stats parser

software/py/vanilla_pc_histogram.py
Previously we had the number of times each basic block is executed. Now we also count number of cycles spend on the PCs inside that basic block, which includes stalls, mispredicts, and bubbles.
@mrutt92  I believe this covers what you asked for, let me know!
=> Added counting and printing number of cycles spent on each basic block to PC histogram

software/spmd/bsg_cuda_lite_runtime/memory_leak/Makefile, software/spmd/bsg_cuda_lite_runtime/memory_leak/kernel_memory_leak.cpp, software/spmd/bsg_cuda_lite_runtime/memory_leak/main.c
Related to PR # 578 in bsg_replicant.
=> Added memory_leak cuda lite runtime regression test

software/py/vanilla_parser/stats_parser.py
For counting the absolute cycle count, we should find the earliest _start_ stat and the latest _end_ stat for all tiles and subtract. This used to be done for tile groups, but for the entire network, each stat was mistakenly being considered as both start and end stat which was wrong.
=> Bug fix, changed counting absolute cycles for the entire manycore

.gitlab-ci.yml
Removed manual clone of DRAMSim3 to fix CI
=> Fix CI for DRAMSim3

software/spmd/bsg_cuda_lite_runtime/profiler/Makefile, software/spmd/bsg_cuda_lite_runtime/profiler/kernel.cpp, software/spmd/bsg_cuda_lite_runtime/profiler/main.c
* Runs single-tile matrix multiply
=> Added profiler test for replicant

software/spmd/bsg_cuda_lite_runtime/tracer/Makefile, software/spmd/bsg_cuda_lite_runtime/tracer/kernel_vec_add_parallel.cpp, software/spmd/bsg_cuda_lite_runtime/tracer/main.c
This test performs parallel vector add
We use this to demonstrate the tracers in replicant.
=> Added tracer regression test (for Replicant)

machines/arch_filelist.mk, testbenches/common/v/bsg_manycore_top_crossbar.v, v/bsg_manycore.v
* Different parts of hierarchy were coming out of reset at different times
* 0'th bit of reset delay was not driven
=> Fixed undriven reset_r index

software/py/vanilla_parser/stats_parser.py
- Also added counting FLOPS/cycle to all stats
- updated commentary
=> Fixed bug in double counting vcache stats

software/spmd/quicktouch/main.c
Reduces the nbf file from 2000s to 445.
=> [quicktouch] shorten quicktouch for gate-level sim test

testbenches/common/v/bsg_manycore_vcache_wh_to_cache_dma.v, testbenches/common/v/bsg_nonsynth_manycore_testbench.v, testbenches/common/v/bsg_nonsynth_wormhole_test_mem.v, testbenches/common/v/spmd_testbench.v, v/bsg_manycore_pod_ruche.v, v/bsg_manycore_pod_ruche_array.v, v/bsg_manycore_tile_vcache_array.v
Move wormhole concentrator outside pod ruche array to accommodate to top-level design infrastructure
SPMD testbench updated accordingly
=> Move wormhole concentrator outside pod ruche array

software/spmd/bsg_cuda_lite_runtime/dma/Makefile, software/spmd/bsg_cuda_lite_runtime/dma/kernel_dma.cpp, software/spmd/bsg_cuda_lite_runtime/dma/main.c, testbenches/dpi/bsg_nonsynth_dpi_manycore.hpp, testbenches/dpi/bsg_nonsynth_dpi_manycore.v
Changes to test bench code to accommodate CUDA Lite updates for BigBlade.
=> Reset done dpi

software/py/vanilla_parser/vcache_stall_graph.py, testbenches/common/v/vcache_profiler.v
A similar problem was solved in #426 (IIRC) but this was not added to the profiler.
=> Add stall_rsp to vcache trace graph (orange)

testbenches/common/v/bsg_nonsynth_mem_infinite.v
This PR adds support for the packet type e_remote_sw to the infinite memory module.
=> Store words to infinite memory

software/py/vanilla_parser/stats_parser.py, testbenches/common/v/bsg_nonsynth_manycore_testbench.v
Parser fixes in master, now applied to bigblade. 
#428 fixes the cache profiler
#480 fixes an issue with statistics counting
The final commit fixes an issue with the header_print_p parameter. Otherwise, the header in vcache_stats is not printed
=> Parser fixes 

testbenches/dpi/bsg_nonsynth_dpi_manycore.hpp, testbenches/dpi/bsg_nonsynth_dpi_manycore.v
* Change credit handling from count down to count up
* Add DPI methods for tracking response fifo capacity
* Add DPI response functionality
=> Updated DPI interface for endpoint credit refactor

ci/interrupt.sh, software/spmd/Makefile, software/spmd/beebs/Makefile, software/spmd/interrupt_tests/Makefile
* Add check_finish command to interrupt CI
=> Unify make summary command for all test suites

software/mk/Makefile.verilog, software/spmd/beebs/Makefile, testbenches/common/v/bsg_nonsynth_manycore_spmd_loader.v
I also decreased the beebs iteration count to reduce runtime there. Is it critical to run them twice?
=> Increased timeout for testbenches

software/spmd/vcache_atomic_histogram/main.c
* Speeds up simulation on 1x1 pod by ~2x
=> Change vcache_atomic_histogram to bsg_print_int

v/vanilla_bean/vanilla_core.v
=> Fixing inferred datapath latch

v/bsg_manycore_pod_ruche_row.v, v/bsg_manycore_tile_compute_array_mesh.v, v/bsg_manycore_tile_compute_array_ruche.v, v/vanilla_bean/bsg_vanilla_pkg.v
=> Minor synthesis fixes

software/bsg_manycore_lib/bsg_tile_group_barrier.h
If this file is included in multiple .c files that are independently
compiled into .o files, the linker will complain about duplicate
symbols.
=> Added missing inline

v/vanilla_bean/bsg_vanilla_defines.vh, v/vanilla_bean/bsg_vanilla_pkg.v, v/vanilla_bean/lsu.v, v/vanilla_bean/vanilla_core.v
Removing unnecessary flops that store sign-extended bits.
=> mem_addr_op2 width opt

testbenches/common/v/vanilla_core_profiler.v
=> update vanilla core profiler

software/bsg_manycore_lib/bsg_manycore.h, software/spmd/energy_loop_test/Makefile, software/spmd/energy_lr_aq_test/Makefile, software/spmd/energy_lr_aq_test/main.c
energy_lr_aq_test and other updates
=> Energy benchmark update

machines/Makefile.vcs, testbenches/common/v/bsg_nonsynth_manycore_testbench.v, testbenches/common/v/spmd_testbench.v, testbenches/common/v/vanilla_core_trace.v
Updating vanilla_core_trace and adding it to the debug mode (WAVE=1)
=> Vanilla core trace update

v/vanilla_bean/network_tx.v
This PR fixes the functional bug described in this test
https://github.com/bespoke-silicon-group/bsg_manycore/pull/628
=> Credit pkt regfile corrupt fix

software/py/nbf_blackparrot.py
This PR updates the BP NBF to reflect latest changes in the BP configuration address space.
=> Update BP NBF

.gitignore, machines/.gitignore, machines/Makefile, machines/Makefile.xcelium, machines/platform.mk, machines/xcelium_dump.tcl, software/mk/Makefile.paths, software/mk/Makefile.tail_rules, software/mk/Makefile.verilog, testbenches/common/v/bsg_manycore_crossbar.v
This commit adds support for xcelium. It does not use multicore, plusperf, or other performance optimizations. However, it does add dumping and waveform viewing.
It also has a few fixes
=> Initial xcelium commit

v/bsg_manycore_link_to_cache.v, v/bsg_manycore_tile_vcache.v
Related: https://github.com/bespoke-silicon-group/basejump_stl/pull/639
=> [bsg_cache] update ready_o -> yumi_o

software/bsg_manycore_lib/bsg_hw_barrier_config_init.h, testbenches/common/v/bsg_nonsynth_manycore_testbench.v, v/bsg_manycore_pod_ruche_array.v, v/bsg_manycore_pod_ruche_row.v, v/bsg_manycore_tile_compute_array_ruche.v, v/bsg_manycore_tile_compute_ruche.v, v/chip/bsg_manycore_link_ruche_to_sdr.vh
- Enabling ruche_factor_X_p  >= 2
=> Varying ruche factor

software/py/pc_histogram.py, testbenches/common/v/vanilla_core_pc_histogram.v
- Adding stall_depend_seq_dram, stall_depend_dram_amo (originally subset of stall_depend_dram)
=> update pc histogram

.gitignore, machines/Makefile.surelog, machines/Makefile.verilator, machines/Makefile.xcelium, machines/platform.mk, software/mk/Makefile.tail_rules, testbenches/common/v/vanilla_core_profiler.sv, v/bsg_manycore_accel_default.sv, v/bsg_manycore_gather_scatter.sv
This PR fixes the verilator xcelium and surelog builds by adding the recently added #715 definition.
=> Adding ipoly definition

v/bsg_manycore_tile_compute_array_mesh.sv
Fixing
https://github.com/bespoke-silicon-group/bsg_manycore/issues/696#issuecomment-2353006461
=> [bsg_manycore_tile_compute_array_mesh] Minor Fix

software/spmd/Makefile, software/spmd/hb_mc_00_local_dmem/Makefile, software/spmd/hb_mc_00_local_dmem/main.S, software/spmd/hb_mc_01_vcache_dram/Makefile, software/spmd/hb_mc_01_vcache_dram/main.c, software/spmd/hb_mc_02_noc_intrapod/Makefile, software/spmd/hb_mc_02_noc_intrapod/main.c, software/spmd/hb_mc_03_icache/Makefile, software/spmd/hb_mc_03_icache/main.S, software/spmd/hb_mc_04_noc_interpod/Makefile, software/spmd/hb_mc_04_noc_interpod/main.c, software/spmd/hb_mc_05_regfile/Makefile, software/spmd/hb_mc_05_regfile/main.S, software/spmd/hb_mc_06_icache_miss/Makefile, software/spmd/hb_mc_06_icache_miss/main.S, software/spmd/hb_mc_07_vcache_dram_prbs/Makefile, software/spmd/hb_mc_07_vcache_dram_prbs/main.c, software/spmd/hb_mc_08_power_burning/Makefile, software/spmd/hb_mc_08_power_burning/main.S, software/spmd/hb_mc_09_power_high_freq/Makefile, software/spmd/hb_mc_09_power_high_freq/count.c, software/spmd/hb_mc_09_power_high_freq/main.c, software/spmd/hb_mc_09_power_high_freq/test.c, software/spmd/hb_mc_10_sdr_init_full/Makefile, software/spmd/hb_mc_10_sdr_init_full/main.c, software/spmd/hb_mc_11_sdr_init_half/Makefile, software/spmd/hb_mc_11_sdr_init_half/main.c, software/spmd/hb_mc_12_sdr_prbs_half/Makefile, software/spmd/hb_mc_12_sdr_prbs_half/main.c
Adding hb_mc test series to run on the fpga system
Must merge after merging [bsg_replicant PR 845](https://github.com/bespoke-silicon-group/bsg_replicant/pull/845)
---------
Co-authored-by: Tommy Jung <tommy.dc.jung@gmail.com>
=> Add HB_MC SPMD Test Series

software/mk/Makefile.builddefs
=> Fix CLANG path

software/spmd/hb_mc_10_sdr_init_full/main.c, software/spmd/hb_mc_13_sdr_prbs_full/Makefile, software/spmd/hb_mc_13_sdr_prbs_full/main.c
Update hb_mc test suite for full 4x4 pods
=> Full 4x4 sdr prbs
